#!/usr/bin/env bash
# Configure a new Nginx server so that /redirect_me is redirecting to another page
#+ The redirection must be a “301 Moved Permanently”

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
ufw allow 80

echo "Hello World!" > /var/www/html/index.html

str="server_name_;\n\trewrite ^/redirect_me https:\/\/www.youtube.com permanent;"
sed -i "s/server_name _;/$str/" /etc/nginx/sites-enabled/default
service nginx restart
