#!/usr/bin/env bash
# Install and configure HAProxy

sudo apt-get update -y
sudo apt-get install -y haproxy

sudo echo "ENABLED=1" >> sudo /etc/default/haproxy

echo "
frontend hbnbclone
    bind *:80
    option forwardfor
    default_backend myservers

backend myservers
    balance roundrobin
    server 279230-web-01 35.175.132.151 check port 80
    server 279230-web-02 35.153.52.85 check port 80
    option httpchk
    option httpclose
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
