#!/usr/bin/env bash
# Creating a bash script that that uses ssh to connect
# to your server using the private key ~/.ssh/school
# with the user ubuntu.

# You do not need to handle the case of a private key 
# protected by a passphrase 

ssh ubuntu -i ~/.ssh/school
